/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button'];
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox'];
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup'];
    ACol: (typeof import('ant-design-vue/es'))['Col'];
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider'];
    AForm: (typeof import('ant-design-vue/es'))['Form'];
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem'];
    AInput: (typeof import('ant-design-vue/es'))['Input'];
    AInputNumber: (typeof import('ant-design-vue/es'))['InputNumber'];
    ALayout: (typeof import('ant-design-vue/es'))['Layout'];
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent'];
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader'];
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider'];
    AMenu: (typeof import('ant-design-vue/es'))['Menu'];
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem'];
    ARadio: (typeof import('ant-design-vue/es'))['Radio'];
    ARadioButton: (typeof import('ant-design-vue/es'))['RadioButton'];
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup'];
    ARate: (typeof import('ant-design-vue/es'))['Rate'];
    AResult: (typeof import('ant-design-vue/es'))['Result'];
    ARow: (typeof import('ant-design-vue/es'))['Row'];
    ASelect: (typeof import('ant-design-vue/es'))['Select'];
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption'];
    ASlider: (typeof import('ant-design-vue/es'))['Slider'];
    ASwitch: (typeof import('ant-design-vue/es'))['Switch'];
    ATable: (typeof import('ant-design-vue/es'))['Table'];
    ATableSummary: (typeof import('ant-design-vue/es'))['TableSummary'];
    ATableSummaryCell: (typeof import('ant-design-vue/es'))['TableSummaryCell'];
    ATableSummaryRow: (typeof import('ant-design-vue/es'))['TableSummaryRow'];
    AUpload: (typeof import('ant-design-vue/es'))['Upload'];
    AUploadDragger: (typeof import('ant-design-vue/es'))['UploadDragger'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
